name: Jest Tests

on:
  issue_comment:
    types: [created]

jobs:
  set_pending:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-tests')
    name: Set PR Pending
    runs-on: ubuntu-22.04
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

  run_tests:
    name: Run Tests
    runs-on: ubuntu-22.04
    needs: set_pending
    strategy:
      fail-fast: false
      matrix:
        status: [success, error]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 17.x
        uses: actions/setup-node@v3
        with:
            node-version: 17

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Dump GitHub input context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: run_tests
        uses: dalevfenton/jest-coverage-report-action@main
        with:
          test-script: npm test -- --ci --coverage --maxWorkers=2
          package-manager: npm
          skip-step: install
          annotations: none
          prnumber: ${{ github.event.issue.number }}
          debug: ${{ matrix.status == 'error' }}

      - name: Dump run-tests context
        if: ${{ success() || failure() }}
        env:
          STEP_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "$STEP_CONTEXT"

      - name: Save Job Output
        if: ${{ success() || failure() }}
        uses: cloudposse/github-action-matrix-outputs-write@main
        id: out
        with:
          matrix-step-name: run_tests
          matrix-key: ${{ matrix.status }}-status
          outputs: |-
            input: ${{ matrix.status }}
            output: ${{ job.status }}

  read:
    if: always()
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: run_tests
      - name: Dump matrix output
        env:
          MATRIX_CONTEXT: ${{ toJson(steps.read.outputs.result) }}
        run: |
          echo "$MATRIX_CONTEXT"
    outputs:
      result: "${{ steps.read.outputs.result }}"

  set_completed_status:
    if: always()
    name: Set Completed Status
    runs-on: ubuntu-22.04
    needs: read
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Dump Jobs context
        env:
          JOBS_CONTEXT: ${{ toJson(needs) }}
        run: |
          echo "$JOBS_CONTEXT"
      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ (fromJson(needs.read.outputs.result).output.error == 'success' && fromJson(needs.read.outputs.result).output.success == 'success') && 'success' || 'failure' }}