name: Jest Tests

on:
  issue_comment:
    types: [created]

jobs:
  run_tests:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-tests')
    name: Run Jest Tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        status: [success, error]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Use Node 17.x
        uses: actions/setup-node@v2
        with:
            node-version: 17.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Run Tests and Comment
        uses: dalevfenton/jest-coverage-report-action@main
        with:
          test-script: npm test -- --ci --coverage --maxWorkers=2
          package-manager: npm
          skip-step: install
          annotations: none
          prnumber: ${{ github.event.issue.number }}
          debug: contains(matrix.status, 'error')

