name: Jest Tests

on:
  issue_comment:
    types: [created]

jobs:
  set_pending:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-tests')
    name: Set PR Pending
    runs-on: ubuntu-22.04
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

  run_tests:
    name: ${{ matrix.status }}-tests
    runs-on: ubuntu-22.04
    needs: set_pending
    strategy:
      fail-fast: false
      matrix:
        status: [success, error]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Use Node 17.x
        uses: actions/setup-node@v3
        with:
            node-version: 17

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Run Tests and Comment
        uses: dalevfenton/jest-coverage-report-action@main
        with:
          test-script: npm test -- --ci --coverage --maxWorkers=2
          package-manager: npm
          skip-step: install
          annotations: none
          prnumber: ${{ github.event.issue.number }}
          debug: ${{ matrix.status == 'error' }}

  set_completed_status:
    if: always()
    name: Set Completed Status
    runs-on: ubuntu-22.04
    needs: [success-tests, error-tests]
    steps:
      - name: Dump Jobs context
        env:
          JOBS_CONTEXT: ${{ toJson(needs) }}
        run: |
          echo "$JOBS_CONTEXT"
      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}